CREATE  TABLE keplersc.ifz_sofia_notif (
  id_sofia_notif serial NOT NULL,
  serie character varying(20) NOT NULL,
  sucursal character varying(2) NOT NULL,
  genero character varying(1) NOT NULL DEFAULT ''::character varying,
  naturaleza character varying(1) NOT NULL DEFAULT ''::character varying,
  grupo numeric NOT NULL DEFAULT 0,
  tipo numeric NOT NULL DEFAULT 0,
  folio character varying(10) NOT NULL DEFAULT ''::character varying,
  fecha timestamp without time zone NOT NULL DEFAULT now(),
  movto_sofia character varying(30) NOT NULL DEFAULT ''::character varying,
  notif_estatus character varying(1) NOT NULL DEFAULT 'P'::character varying,
  notif_fecha timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  notif_mensaje character varying(500) NOT NULL DEFAULT ''::character varying,
  sofia_estatus character varying(1) NOT NULL DEFAULT 'P'::character varying,
  sofia_fecha timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  sofia_mensaje character varying(500) NOT NULL DEFAULT ''::character varying,
  invnot_dealerbac numeric NOT NULL DEFAULT 0,
  invnot_secondarydealernumberid numeric NOT NULL DEFAULT 0,
  invnot_dealerid numeric NOT NULL DEFAULT 0,
  invnot_identificadordocumento numeric NOT NULL DEFAULT 0,
  invnot_fechafactura character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_cadenaoriginaltimbre character varying(500) NOT NULL DEFAULT ''::character varying,
  invnot_idsofia character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_rfc character varying(13) NOT NULL DEFAULT ''::character varying,
  invnot_idcliente numeric NOT NULL DEFAULT 0,
  invnot_numeroidentificacion character varying(25) NOT NULL DEFAULT ''::character varying,
  invnot_tipocliente character varying(1) NOT NULL DEFAULT ''::character varying,
  invnot_codigoactividadeconomica character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_curp character varying(18) NOT NULL DEFAULT ''::character varying,
  invnot_nombre character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidopaterno character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidomaterno character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_nombrecompleto character varying(100) NOT NULL DEFAULT ''::character varying,
  invnot_titulo character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_sexo character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_fechanacimiento character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_calle character varying(100) NOT NULL DEFAULT ''::character varying,
  invnot_numeroexterior character varying(25) NOT NULL DEFAULT ''::character varying,
  invnot_numerointerior character varying(25) NOT NULL DEFAULT ''::character varying,
  invnot_entrecalles character varying(100) NOT NULL DEFAULT ''::character varying,
  invnot_codigoasentamiento character varying(9) NOT NULL DEFAULT ''::character varying,
  invnot_colonia character varying(100) NOT NULL DEFAULT ''::character varying,
  invnot_codigomunicipio character varying(6) NOT NULL DEFAULT ''::character varying,
  invnot_municipio character varying(200) NOT NULL DEFAULT ''::character varying,
  invnot_codigopostal character varying(5) NOT NULL DEFAULT ''::character varying,
  invnot_codigoestado character varying(2) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefono character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefono character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefonooficina character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefonooficina character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefonocelular character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefonocelular character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_email character varying(50) NOT NULL DEFAULT ''::character varying,
  invnot_permitecontacto character varying(2) NOT NULL DEFAULT ''::character varying,
  invnot_nombreconductor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidopaternoconductor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidomaternoconductor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefonoconductor character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefonoconductor character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefonooficinaconductor character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefonooficinaconductor character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_ladatelefonocelularconductor character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_telefonocelularconductor character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_emailconductor character varying(50) NOT NULL DEFAULT ''::character varying,
  invnot_permitecontactoconductor character varying(2) NOT NULL DEFAULT ''::character varying,
  invnot_rfcvendedor character varying(13) NOT NULL DEFAULT ''::character varying,
  invnot_tipodistribuidor character varying(20) NOT NULL DEFAULT ''::character varying,
  invnot_identificadorvendedor character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_nombrevendedor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidopaternovendedor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_apellidomaternovendedor character varying(30) NOT NULL DEFAULT ''::character varying,
  invnot_tipopago character varying(1) NOT NULL DEFAULT ''::character varying,
  invnot_tasa numeric(9,2) NOT NULL DEFAULT 0,
  invnot_plazo numeric NOT NULL DEFAULT 0,
  invnot_numeroautorizacionfinanciamiento character varying(15) NOT NULL DEFAULT ''::character varying,
  invnot_importeventatotal numeric(12,4) NOT NULL DEFAULT 0,
  invnot_enganche numeric(12,4) NOT NULL DEFAULT 0,
  invnot_saldopendiente numeric(12,4) NOT NULL DEFAULT 0,
  invnot_tipoiva character varying(10) NOT NULL DEFAULT ''::character varying,
  invnot_isan numeric(12,4) NOT NULL DEFAULT 0,
  invnot_porcentajeiva numeric(12,2) NOT NULL DEFAULT 0,
  invnot_importeiva numeric(12,4) NOT NULL DEFAULT 0,
  invnot_codigoincentivo character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_codigotipoventa character varying(3) NOT NULL DEFAULT ''::character varying,
  invnot_numeroserie character varying(17) NOT NULL DEFAULT ''::character varying,
  invnot_codigofan character varying(11) NOT NULL DEFAULT ''::character varying,
  invnot_tipoflotilla character varying(1) NOT NULL DEFAULT ''::character varying,
  invcan_dealerbac numeric NOT NULL DEFAULT 0,
  invcan_secondarydealernumberid numeric NOT NULL DEFAULT 0,
  invcan_codigorazoncancelacion character varying(1) NOT NULL DEFAULT ''::character varying,
  invcan_numeronotacredito numeric NOT NULL DEFAULT 0,
  invcan_codigodistribuidor numeric NOT NULL DEFAULT 0,
  invcan_identificadordocumento numeric NOT NULL DEFAULT 0,
  invcan_fechacancelacionfactura character varying(10) NOT NULL DEFAULT ''::character varying,
  invcan_cadenaoriginaltimbre character varying(500) NOT NULL DEFAULT ''::character varying,
  invcan_numeroserie character varying(17) NOT NULL DEFAULT ''::character varying,
  delnot_dealerbac numeric NOT NULL DEFAULT 0,
  delnot_identificadordocumento numeric NOT NULL DEFAULT 0,
  delnot_nombreclienterecibe character varying(30) NOT NULL DEFAULT ''::character varying,
  delnot_apellidopaternoclienterecibe character varying(30) NOT NULL DEFAULT ''::character varying,
  delnot_apellidomaternoclienterecibe character varying(30) NOT NULL DEFAULT ''::character varying,
  delnot_ladatelefonoclienterecibe character varying(3) NOT NULL DEFAULT ''::character varying,
  delnot_telefonoclienterecibe character varying(10) NOT NULL DEFAULT ''::character varying,
  delnot_ladatelefonooficinaclienterecibe character varying(3) NOT NULL DEFAULT ''::character varying,
  delnot_telefonooficinaclienterecibe character varying(10) NOT NULL DEFAULT ''::character varying,
  delnot_ladatelefonocelularclienterecibe character varying(3) NOT NULL DEFAULT ''::character varying,
  delnot_telefonocelularclienterecibe character varying(10) NOT NULL DEFAULT ''::character varying,
  delnot_emailclienterecibe character varying(50) NOT NULL DEFAULT ''::character varying,
  delnot_permitecontactoclienterecibe character varying(2) NOT NULL DEFAULT ''::character varying,
  delnot_numeroserie character varying(17) NOT NULL DEFAULT ''::character varying,
  delnot_fechaentrega character varying(10) NOT NULL DEFAULT ''::character varying,
  delnot_folioentrega character varying(12) NOT NULL DEFAULT ''::character varying,
  retdel_dealerbac numeric NOT NULL DEFAULT 0,
  retdel_foliodevolucionentrega character varying(12) NOT NULL DEFAULT ''::character varying,
  retdel_identificadordocumento numeric NOT NULL DEFAULT 0,
  retdel_numerotransaccionentrega numeric NOT NULL DEFAULT 0,
  retdel_numeroserie character varying(17) NOT NULL DEFAULT ''::character varying,
  retdel_folioentrega character varying(12) NOT NULL DEFAULT ''::character varying,
  demo_vin character varying(17) NOT NULL DEFAULT ''::character varying,
  demo_consec numeric NOT NULL DEFAULT 0,
  demo_idcliente numeric NOT NULL DEFAULT 0,
  demo_estatus character varying(5) NOT NULL DEFAULT ''::character varying,
  demo_notransaccion numeric NOT NULL DEFAULT 0,
  demo_idoperacion numeric NOT NULL DEFAULT 0,
  demo_origenope character varying(15) NOT NULL DEFAULT ''::character varying,
  demo_evento character varying(15) NOT NULL DEFAULT ''::character varying,
  demo_resultado character varying(15) NOT NULL DEFAULT ''::character varying,
  demo_resdescrip character varying(1000) NOT NULL DEFAULT ''::character varying,
  demo_fechact character varying(10) NOT NULL DEFAULT ''::character varying,
  demo_horaact character varying(10) NOT NULL DEFAULT ''::character varying,
  demo_cveusu character varying(5) NOT NULL DEFAULT ''::character varying,
  demo_valorunidad numeric NOT NULL DEFAULT 0,
  demo_ivaaplicable numeric NOT NULL DEFAULT 0,
  sof_numeroregistro numeric NOT NULL DEFAULT 0,
  CONSTRAINT ifz_sofia_notif_unique UNIQUE (serie, movto_sofia, fecha, sucursal)
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.ifz_sofia_notif ADD CONSTRAINT ifz_sofia_notif_pkey PRIMARY KEY (id_sofia_notif);
CREATE INDEX IF NOT EXISTS ifz_sofia_notif_sucursal_idx ON keplersc.ifz_sofia_notif USING btree (sucursal, genero, naturaleza, grupo, tipo, folio) TABLESPACE pg_default;
COMMENT ON TABLE keplersc.ifz_sofia_notif IS 'Notificaciones Sofia pre envio';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.tipo IS 'Tipo';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.sucursal IS 'Sucursal';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.sofia_mensaje IS 'BP-Sofia Mensaje de envio a sofia';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.sofia_fecha IS 'BP-Sofia Fecha de actualizacion de estatus de envio a sofia';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.sofia_estatus IS 'BP-Sofia Estatus envio a sofia';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.sof_numeroregistro IS 'Consecutivo asignado por sofia';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.serie IS 'Serie';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.notif_mensaje IS 'BP Mensaje pre-envio';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.notif_fecha IS 'BP Fecha de actualizacion de estatus de registro en pre-envio';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.notif_estatus IS 'BP Pendiente, eRror, Enviado';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.naturaleza IS 'Naturaleza';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.movto_sofia IS 'Invoice Notification;Invoice Cancelled;Delivery Notification;Return Delivery';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.id_sofia_notif IS 'Consecutivo de registro';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.grupo IS 'Grupo';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.genero IS 'Genero';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.folio IS 'Folio del movimiento';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.fecha IS 'Fecha del movimiento';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.demo_estatus IS 'PDVIN - Demo In Ventas; PDSIN - Demo in Servicio; PDOUT - Demo Out';
COMMENT ON COLUMN keplersc.ifz_sofia_notif.demo_consec IS 'Consec por vin y demo_estatus';
CREATE TRIGGER ifzsofia_notif AFTER INSERT ON keplersc.ifz_sofia_notif FOR EACH ROW EXECUTE FUNCTION keplersc.notif_registrar_movto();

