CREATE  TABLE keplersc.kdc22608 (
  c1 numeric NOT NULL,
  c2 timestamp without time zone NOT NULL,
  c3 character varying(20) NOT NULL,
  c4 character varying(1) NULL,
  c5 numeric(15,2) NULL,
  c6 character varying(40) NULL,
  c7 character varying(40) NULL,
  c8 character varying(1) NOT NULL,
  c9 numeric(15,4) NULL,
  c10 numeric NOT NULL,
  c11 character varying(1) NULL,
  c12 character varying(1) NULL,
  c13 character varying(10) NULL,
  c14 character varying(7) NULL,
  c15 character varying(1) NULL,
  c16 character varying(1) NULL,
  c17 numeric NULL,
  c18 numeric NULL,
  c19 character varying(10) NULL,
  c20 character varying(10) NULL,
  c21 character varying(10) NULL,
  c22 character varying(7) NULL,
  c23 character varying(1) NULL,
  c24 character varying(1) NULL,
  c25 character varying(1) NULL,
  c26 character varying(1) NULL,
  c27 character varying(1) NULL,
  c28 character varying(1) NULL,
  c29 character varying(1) NULL,
  c30 character varying(20) NULL,
  c31 timestamp without time zone NULL,
  c32 character varying(20) NULL,
  c33 character varying(1) NULL,
  c34 character varying(1) NULL,
  c35 character varying(1) NULL,
  c36 character varying(1) NULL,
  c37 character varying(1) NULL,
  c38 character varying(1) NULL,
  c39 character varying(1) NULL,
  c40 character varying(1) NULL,
  c41 character varying(1) NULL,
  c42 character varying(1) NULL,
  c43 character varying(1) NULL,
  c44 character varying(1) NULL,
  c45 character varying(1) NULL,
  c46 character varying(1) NULL,
  c47 character varying(1) NULL,
  c48 character varying(1) NULL,
  c49 character varying(1) NULL,
  c50 character varying(1) NULL
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdc22608 ADD CONSTRAINT kdc22608_pkey PRIMARY KEY (c3, c2, c8, c1, c10);
CREATE TRIGGER kdc22608_upd_nivel_after_crud AFTER INSERT OR DELETE OR UPDATE ON keplersc.kdc22608 FOR EACH ROW EXECUTE FUNCTION keplersc.cont_upd_saldos();

