CREATE  TABLE keplersc.kdc22306 (
  c1 numeric NOT NULL,
  c2 timestamp without time zone NOT NULL,
  c3 character varying(20) NOT NULL,
  c4 character varying(1) NOT NULL,
  c5 numeric(15,2) NOT NULL,
  c6 character varying(40) NOT NULL,
  c7 character varying(40) NOT NULL,
  c8 character varying(1) NOT NULL,
  c9 numeric(15,4) NULL DEFAULT 0,
  c10 numeric NOT NULL,
  c11 character varying(1) NULL DEFAULT ''::character varying,
  c12 character varying(1) NULL DEFAULT ''::character varying,
  c13 character varying(10) NULL DEFAULT ''::character varying,
  c14 character varying(7) NOT NULL,
  c15 character varying(1) NOT NULL,
  c16 character varying(1) NOT NULL,
  c17 numeric NOT NULL,
  c18 numeric NOT NULL,
  c19 character varying(10) NOT NULL,
  c20 character varying(10) NULL DEFAULT ''::character varying,
  c21 character varying(10) NULL DEFAULT ''::character varying,
  c22 character varying(7) NULL DEFAULT ''::character varying,
  c23 character varying(1) NULL DEFAULT ''::character varying,
  c24 character varying(1) NULL DEFAULT ''::character varying,
  c25 character varying(1) NULL DEFAULT ''::character varying,
  c26 character varying(1) NULL DEFAULT ''::character varying,
  c27 character varying(1) NULL DEFAULT ''::character varying,
  c28 character varying(1) NULL DEFAULT ''::character varying,
  c29 character varying(1) NULL DEFAULT ''::character varying,
  c30 character varying(20) NULL DEFAULT ''::character varying,
  c31 timestamp without time zone NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c32 character varying(20) NULL DEFAULT ''::character varying,
  c33 character varying(1) NULL DEFAULT ''::character varying,
  c34 character varying(1) NULL DEFAULT ''::character varying,
  c35 character varying(1) NULL DEFAULT ''::character varying,
  c36 character varying(1) NULL DEFAULT ''::character varying,
  c37 character varying(1) NULL DEFAULT ''::character varying,
  c38 character varying(1) NULL DEFAULT ''::character varying,
  c39 character varying(1) NULL DEFAULT ''::character varying,
  c40 character varying(1) NULL DEFAULT ''::character varying,
  c41 character varying(1) NULL DEFAULT ''::character varying,
  c42 character varying(1) NULL DEFAULT ''::character varying,
  c43 character varying(1) NULL DEFAULT ''::character varying,
  c44 character varying(1) NULL DEFAULT ''::character varying,
  c45 character varying(1) NULL DEFAULT ''::character varying,
  c46 character varying(1) NULL DEFAULT ''::character varying,
  c47 character varying(1) NULL DEFAULT ''::character varying,
  c48 character varying(1) NULL DEFAULT ''::character varying,
  c49 character varying(1) NULL DEFAULT ''::character varying,
  c50 character varying(1) NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdc22306 ADD CONSTRAINT pk_kdc22306 PRIMARY KEY (c3, c2, c8, c1, c10);
CREATE INDEX IF NOT EXISTS sindkdc2230602 ON keplersc.kdc22306 USING btree (c8, c1, c10) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdc2230603 ON keplersc.kdc22306 USING btree (c2, c8, c1, c10) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdc2230604 ON keplersc.kdc22306 USING btree (c13, c2, c3, c8, c1, c10) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdc2230605 ON keplersc.kdc22306 USING btree (c14, c15, c16, c17, c18, c19, c8, c1, c10) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdc2230606 ON keplersc.kdc22306 USING btree (c21, c2, c3, c8, c1, c10) TABLESPACE pg_default;
CREATE TRIGGER kdc22306_upd_saldos_after_crud AFTER INSERT OR DELETE OR UPDATE ON keplersc.kdc22306 FOR EACH ROW EXECUTE FUNCTION keplersc.cont_upd_saldos();

