CREATE  TABLE keplersc.kdfecfd (
  c1 character varying(7) NOT NULL DEFAULT ''::character varying,
  c2 character varying(10) NOT NULL DEFAULT ''::character varying,
  c3 numeric NOT NULL DEFAULT 0,
  c4 numeric NOT NULL DEFAULT 0,
  c5 character varying(1) NOT NULL DEFAULT ''::character varying,
  c6 numeric NOT NULL DEFAULT 0,
  c7 numeric NOT NULL DEFAULT 0,
  c8 character varying(20) NOT NULL DEFAULT ''::character varying,
  c9 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c10 character varying(20) NOT NULL DEFAULT ''::character varying,
  c11 character varying(1) NOT NULL DEFAULT ''::character varying,
  c12 character varying(1) NOT NULL DEFAULT ''::character varying,
  c13 character varying(1) NOT NULL DEFAULT ''::character varying,
  c14 numeric NOT NULL DEFAULT 0,
  c15 numeric NOT NULL DEFAULT 0,
  c16 character varying(7) NOT NULL DEFAULT ''::character varying,
  c17 character varying(1) NOT NULL DEFAULT ''::character varying,
  c18 character varying(5) NOT NULL DEFAULT ''::character varying,
  c19 character varying(10) NOT NULL DEFAULT ''::character varying,
  c20 character varying(30) NOT NULL DEFAULT ''::character varying,
  c21 character varying(30) NOT NULL DEFAULT ''::character varying,
  c22 character varying(60) NOT NULL DEFAULT ''::character varying,
  c23 numeric(20,6) NOT NULL DEFAULT 0,
  c24 numeric(20,6) NOT NULL DEFAULT 0,
  c25 numeric(20,6) NOT NULL DEFAULT 0,
  c26 character varying(1) NOT NULL DEFAULT ''::character varying,
  c27 character varying(13) NOT NULL DEFAULT ''::character varying,
  c28 character varying(70) NOT NULL DEFAULT ''::character varying,
  c29 character varying(60) NOT NULL DEFAULT ''::character varying,
  c30 character varying(10) NOT NULL DEFAULT ''::character varying,
  c31 character varying(10) NOT NULL DEFAULT ''::character varying,
  c32 character varying(60) NOT NULL DEFAULT ''::character varying,
  c33 character varying(60) NOT NULL DEFAULT ''::character varying,
  c34 character varying(60) NOT NULL DEFAULT ''::character varying,
  c35 character varying(60) NOT NULL DEFAULT ''::character varying,
  c36 character varying(60) NOT NULL DEFAULT ''::character varying,
  c37 character varying(60) NOT NULL DEFAULT ''::character varying,
  c38 character varying(10) NOT NULL DEFAULT ''::character varying,
  c39 character varying(1) NOT NULL DEFAULT ''::character varying,
  c40 character varying(60) NOT NULL DEFAULT ''::character varying,
  c41 character varying(10) NOT NULL DEFAULT ''::character varying,
  c42 character varying(10) NOT NULL DEFAULT ''::character varying,
  c43 character varying(60) NOT NULL DEFAULT ''::character varying,
  c44 character varying(60) NOT NULL DEFAULT ''::character varying,
  c45 character varying(60) NOT NULL DEFAULT ''::character varying,
  c46 character varying(60) NOT NULL DEFAULT ''::character varying,
  c47 character varying(60) NOT NULL DEFAULT ''::character varying,
  c48 character varying(60) NOT NULL DEFAULT ''::character varying,
  c49 character varying(10) NOT NULL DEFAULT ''::character varying,
  c50 character varying(1) NOT NULL DEFAULT ''::character varying,
  c51 character varying(13) NOT NULL DEFAULT ''::character varying,
  c52 character varying(60) NOT NULL DEFAULT ''::character varying,
  c53 character varying(60) NOT NULL DEFAULT ''::character varying,
  c54 character varying(10) NOT NULL DEFAULT ''::character varying,
  c55 character varying(10) NOT NULL DEFAULT ''::character varying,
  c56 character varying(60) NOT NULL DEFAULT ''::character varying,
  c57 character varying(60) NOT NULL DEFAULT ''::character varying,
  c58 character varying(60) NOT NULL DEFAULT ''::character varying,
  c59 character varying(60) NOT NULL DEFAULT ''::character varying,
  c60 character varying(60) NOT NULL DEFAULT ''::character varying,
  c61 character varying(60) NOT NULL DEFAULT ''::character varying,
  c62 character varying(10) NOT NULL DEFAULT ''::character varying,
  c63 character varying(1) NOT NULL DEFAULT ''::character varying,
  c64 numeric(20,6) NOT NULL DEFAULT 0,
  c65 numeric(20,6) NOT NULL DEFAULT 0,
  c66 numeric(20,6) NOT NULL DEFAULT 0,
  c67 numeric(20,6) NOT NULL DEFAULT 0,
  c68 numeric(20,6) NOT NULL DEFAULT 0,
  c69 character varying(1) NOT NULL DEFAULT ''::character varying,
  c70 character varying(200) NOT NULL DEFAULT ''::character varying,
  c71 character varying(100) NOT NULL DEFAULT ''::character varying,
  c72 character varying(100) NOT NULL DEFAULT ''::character varying,
  c73 character varying(20) NOT NULL DEFAULT ''::character varying,
  c74 character varying(150) NOT NULL DEFAULT ''::character varying,
  c75 character varying(100) NOT NULL DEFAULT ''::character varying,
  c76 character varying(1) NOT NULL DEFAULT ''::character varying,
  c77 character varying(5) NOT NULL DEFAULT ''::character varying,
  c78 numeric(20,6) NOT NULL DEFAULT 0,
  c79 character varying(1) NOT NULL DEFAULT ''::character varying,
  c80 character varying(5) NOT NULL DEFAULT ''::character varying,
  c81 character varying(36) NOT NULL DEFAULT ''::character varying,
  c82 character varying(20) NOT NULL DEFAULT ''::character varying,
  c83 character varying(20) NOT NULL DEFAULT ''::character varying,
  c84 character varying(200) NOT NULL DEFAULT ''::character varying,
  c85 character varying(30) NOT NULL DEFAULT ''::character varying,
  c86 character varying(150) NOT NULL DEFAULT ''::character varying,
  c87 character varying(1) NOT NULL DEFAULT ''::character varying,
  c88 character varying(18) NOT NULL DEFAULT ''::character varying,
  c89 character varying(125) NOT NULL DEFAULT ''::character varying,
  c90 character varying(10) NOT NULL DEFAULT ''::character varying,
  c91 character varying(36) NOT NULL DEFAULT ''::character varying,
  c92 character varying(20) NOT NULL DEFAULT ''::character varying,
  c93 numeric(20,6) NOT NULL DEFAULT 0,
  c94 character varying(80) NOT NULL DEFAULT ''::character varying,
  c95 character varying(80) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdfecfd ADD CONSTRAINT pk_kdfecfd PRIMARY KEY (c1, c2, c3);
CREATE INDEX IF NOT EXISTS sindkdfecfd02 ON keplersc.kdfecfd USING btree (c2, c3, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfecfd03 ON keplersc.kdfecfd USING btree (c1, c12, c13, c14, c15, c16) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfecfd04 ON keplersc.kdfecfd USING btree (c8, c1, c2, c3) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfecfd05 ON keplersc.kdfecfd USING btree (c6, c7, c1, c2, c3) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfecfd06 ON keplersc.kdfecfd USING btree (c4, c10, c2, c3, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfecfd07 ON keplersc.kdfecfd USING btree (c81, c1, c2, c3) TABLESPACE pg_default;

