CREATE  TABLE keplersc.kdprosp (
  c1 character varying(10) NOT NULL DEFAULT ''::character varying,
  c2 character varying(1) NOT NULL DEFAULT ''::character varying,
  c3 character varying(60) NOT NULL DEFAULT ''::character varying,
  c4 character varying(30) NOT NULL DEFAULT ''::character varying,
  c5 character varying(50) NOT NULL DEFAULT ''::character varying,
  c6 character varying(80) NOT NULL DEFAULT ''::character varying,
  c7 character varying(6) NOT NULL DEFAULT ''::character varying,
  c8 character varying(3) NOT NULL DEFAULT ''::character varying,
  c9 character varying(3) NOT NULL DEFAULT ''::character varying,
  c10 character varying(7) NOT NULL DEFAULT ''::character varying,
  c11 character varying(3) NOT NULL DEFAULT ''::character varying,
  c12 character varying(3) NOT NULL DEFAULT ''::character varying,
  c13 character varying(7) NOT NULL DEFAULT ''::character varying,
  c14 character varying(3) NOT NULL DEFAULT ''::character varying,
  c15 character varying(3) NOT NULL DEFAULT ''::character varying,
  c16 character varying(7) NOT NULL DEFAULT ''::character varying,
  c17 character varying(3) NOT NULL DEFAULT ''::character varying,
  c18 character varying(3) NOT NULL DEFAULT ''::character varying,
  c19 character varying(7) NOT NULL DEFAULT ''::character varying,
  c20 character varying(15) NOT NULL DEFAULT ''::character varying,
  c21 character varying(80) NOT NULL DEFAULT ''::character varying,
  c22 character varying(50) NOT NULL DEFAULT ''::character varying,
  c23 character varying(50) NOT NULL DEFAULT ''::character varying,
  c24 character varying(30) NOT NULL DEFAULT ''::character varying,
  c25 character varying(20) NOT NULL DEFAULT ''::character varying,
  c26 character varying(5) NOT NULL DEFAULT ''::character varying,
  c27 character varying(1) NOT NULL DEFAULT ''::character varying,
  c28 character varying(50) NOT NULL DEFAULT ''::character varying,
  c29 character varying(50) NOT NULL DEFAULT ''::character varying,
  c30 character varying(50) NOT NULL DEFAULT ''::character varying,
  c31 character varying(50) NOT NULL DEFAULT ''::character varying,
  c32 character varying(50) NOT NULL DEFAULT ''::character varying,
  c33 character varying(50) NOT NULL DEFAULT ''::character varying,
  c34 character varying(50) NOT NULL DEFAULT ''::character varying,
  c35 character varying(50) NOT NULL DEFAULT ''::character varying,
  c36 character varying(50) NOT NULL DEFAULT ''::character varying,
  c37 character varying(50) NOT NULL DEFAULT ''::character varying,
  c38 character varying(50) NOT NULL DEFAULT ''::character varying,
  c39 character varying(50) NOT NULL DEFAULT ''::character varying,
  c40 character varying(50) NOT NULL DEFAULT ''::character varying,
  c41 character varying(50) NOT NULL DEFAULT ''::character varying,
  c42 character varying(50) NOT NULL DEFAULT ''::character varying,
  c43 character varying(50) NOT NULL DEFAULT ''::character varying,
  c44 numeric NOT NULL DEFAULT 0,
  c45 numeric NOT NULL DEFAULT 0,
  c46 character varying(7) NOT NULL DEFAULT ''::character varying,
  c47 character varying(80) NOT NULL DEFAULT ''::character varying,
  c48 character varying(70) NOT NULL DEFAULT ''::character varying,
  c49 character varying(70) NOT NULL DEFAULT ''::character varying,
  c50 character varying(70) NOT NULL DEFAULT ''::character varying,
  c51 character varying(70) NOT NULL DEFAULT ''::character varying,
  c52 character varying(20) NOT NULL DEFAULT ''::character varying,
  c53 character varying(20) NOT NULL DEFAULT ''::character varying,
  c54 character varying(20) NOT NULL DEFAULT ''::character varying,
  c55 character varying(80) NOT NULL DEFAULT ''::character varying,
  c56 character varying(7) NOT NULL DEFAULT ''::character varying,
  c57 character varying(7) NOT NULL DEFAULT ''::character varying,
  c58 character varying(70) NOT NULL DEFAULT ''::character varying,
  c59 character varying(35) NOT NULL DEFAULT ''::character varying,
  c60 character varying(7) NOT NULL DEFAULT ''::character varying,
  c61 character varying(7) NOT NULL DEFAULT ''::character varying,
  c62 character varying(70) NOT NULL DEFAULT ''::character varying,
  c63 character varying(35) NOT NULL DEFAULT ''::character varying,
  c64 character varying(35) NOT NULL DEFAULT ''::character varying,
  c65 character varying(5) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdprosp ADD CONSTRAINT pk_kdprosp PRIMARY KEY (c1);
CREATE INDEX IF NOT EXISTS sindkdprosp02 ON keplersc.kdprosp USING btree (c3, c5, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdprosp03 ON keplersc.kdprosp USING btree (c8, c9, c10, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdprosp04 ON keplersc.kdprosp USING btree (c11, c12, c13, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdprosp05 ON keplersc.kdprosp USING btree (c6, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdprosp06 ON keplersc.kdprosp USING btree (c44, c45, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdprosp07 ON keplersc.kdprosp USING btree (c46, c1) TABLESPACE pg_default;

