CREATE  TABLE keplersc.control_de_citas (
  col_fecha timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  col_clave_operador character varying NOT NULL DEFAULT ''::character varying,
  col_nombre_ope character varying NOT NULL DEFAULT ''::character varying,
  col_tipo_ope character varying NOT NULL DEFAULT ''::character varying,
  h_07_00 character varying NOT NULL DEFAULT ''::character varying,
  h_07_15 character varying NOT NULL DEFAULT ''::character varying,
  h_07_30 character varying NOT NULL DEFAULT ''::character varying,
  h_07_45 character varying NOT NULL DEFAULT ''::character varying,
  h_08_00 character varying NOT NULL DEFAULT ''::character varying,
  h_08_15 character varying NOT NULL DEFAULT ''::character varying,
  h_08_30 character varying NOT NULL DEFAULT ''::character varying,
  h_08_45 character varying NOT NULL DEFAULT ''::character varying,
  h_09_00 character varying NOT NULL DEFAULT ''::character varying,
  h_09_15 character varying NOT NULL DEFAULT ''::character varying,
  h_09_30 character varying NOT NULL DEFAULT ''::character varying,
  h_09_45 character varying NOT NULL DEFAULT ''::character varying,
  h_10_00 character varying NOT NULL DEFAULT ''::character varying,
  h_10_15 character varying NOT NULL DEFAULT ''::character varying,
  h_10_30 character varying NOT NULL DEFAULT ''::character varying,
  h_10_45 character varying NOT NULL DEFAULT ''::character varying,
  h_11_00 character varying NOT NULL DEFAULT ''::character varying,
  h_11_15 character varying NOT NULL DEFAULT ''::character varying,
  h_11_30 character varying NOT NULL DEFAULT ''::character varying,
  h_11_45 character varying NOT NULL DEFAULT ''::character varying,
  h_12_00 character varying NOT NULL DEFAULT ''::character varying,
  h_12_15 character varying NOT NULL DEFAULT ''::character varying,
  h_12_30 character varying NOT NULL DEFAULT ''::character varying,
  h_12_45 character varying NOT NULL DEFAULT ''::character varying,
  h_13_00 character varying NOT NULL DEFAULT ''::character varying,
  h_13_15 character varying NOT NULL DEFAULT ''::character varying,
  h_13_30 character varying NOT NULL DEFAULT ''::character varying,
  h_13_45 character varying NOT NULL DEFAULT ''::character varying,
  h_14_00 character varying NOT NULL DEFAULT ''::character varying,
  h_14_15 character varying NOT NULL DEFAULT ''::character varying,
  h_14_30 character varying NOT NULL DEFAULT ''::character varying,
  h_14_45 character varying NOT NULL DEFAULT ''::character varying,
  h_15_00 character varying NOT NULL DEFAULT ''::character varying,
  h_15_15 character varying NOT NULL DEFAULT ''::character varying,
  h_15_30 character varying NOT NULL DEFAULT ''::character varying,
  h_15_45 character varying NOT NULL DEFAULT ''::character varying,
  h_16_00 character varying NOT NULL DEFAULT ''::character varying,
  h_16_15 character varying NOT NULL DEFAULT ''::character varying,
  h_16_30 character varying NOT NULL DEFAULT ''::character varying,
  h_16_45 character varying NOT NULL DEFAULT ''::character varying,
  h_17_00 character varying NOT NULL DEFAULT ''::character varying,
  h_17_15 character varying NOT NULL DEFAULT ''::character varying,
  h_17_30 character varying NOT NULL DEFAULT ''::character varying,
  h_17_45 character varying NOT NULL DEFAULT ''::character varying,
  h_18_00 character varying NOT NULL DEFAULT ''::character varying,
  h_18_15 character varying NOT NULL DEFAULT ''::character varying,
  h_18_30 character varying NOT NULL DEFAULT ''::character varying,
  h_18_45 character varying NOT NULL DEFAULT ''::character varying,
  h_19_00 character varying NOT NULL DEFAULT ''::character varying,
  h_19_15 character varying NOT NULL DEFAULT ''::character varying,
  h_19_30 character varying NOT NULL DEFAULT ''::character varying,
  h_19_45 character varying NOT NULL DEFAULT ''::character varying,
  h_20_00 character varying NOT NULL DEFAULT ''::character varying,
  h_20_15 character varying NOT NULL DEFAULT ''::character varying,
  h_20_30 character varying NOT NULL DEFAULT ''::character varying,
  h_20_45 character varying NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
CREATE UNIQUE INDEX IF NOT EXISTS control_de_citas_fecha_idx ON keplersc.control_de_citas USING btree (col_fecha, col_clave_operador) TABLESPACE pg_default;
COMMENT ON TABLE keplersc.control_de_citas IS 'panorama de horarios de citas de los operadores';

