CREATE  TABLE keplersc.crdcredit (
  k_branch character varying(20) NOT NULL DEFAULT ''::character varying,
  k_cred numeric NOT NULL DEFAULT 0,
  k_cust character varying(20) NOT NULL DEFAULT ''::character varying,
  k_type character varying(10) NOT NULL DEFAULT ''::character varying,
  k_sch numeric NOT NULL DEFAULT 0,
  k_date timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  k_m double precision NOT NULL DEFAULT 0,
  k_currency character varying(10) NOT NULL DEFAULT ''::character varying,
  k_n numeric NOT NULL DEFAULT 0,
  k_g numeric NOT NULL DEFAULT 0,
  k_dpp numeric NOT NULL DEFAULT 0,
  k_p double precision NOT NULL DEFAULT 0,
  k_base character varying(7) NOT NULL DEFAULT ''::character varying,
  k_int double precision NOT NULL DEFAULT 0,
  k_basem character varying(7) NOT NULL DEFAULT ''::character varying,
  k_intm double precision NOT NULL DEFAULT 0,
  k_fm double precision NOT NULL DEFAULT 0,
  k_basei character varying(7) NOT NULL DEFAULT ''::character varying,
  k_inti double precision NOT NULL DEFAULT 0,
  k_fi double precision NOT NULL DEFAULT 0,
  k_basep character varying(7) NOT NULL DEFAULT ''::character varying,
  k_intp double precision NOT NULL DEFAULT 0,
  k_fp double precision NOT NULL DEFAULT 0,
  k_pay1 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  k_int_antic numeric NOT NULL DEFAULT 0,
  k_next numeric NOT NULL DEFAULT 0,
  k_day numeric NOT NULL DEFAULT 0,
  k_first numeric NOT NULL DEFAULT 0,
  k_calc numeric NOT NULL DEFAULT 0,
  k_mor numeric NOT NULL DEFAULT 0,
  k_last timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  k_mult numeric NOT NULL DEFAULT 0,
  k_dif numeric NOT NULL DEFAULT 0,
  k_cap numeric NOT NULL DEFAULT 0,
  k_nmult numeric NOT NULL DEFAULT 0,
  k_p2 double precision NOT NULL DEFAULT 0,
  k_cap_n numeric NOT NULL DEFAULT 0,
  k_margin numeric NOT NULL DEFAULT 0,
  k_int_def double precision NOT NULL DEFAULT 0,
  k_residual double precision NOT NULL DEFAULT 0,
  k_f_tax double precision NOT NULL DEFAULT 0,
  k_source character varying(7) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.crdcredit ADD CONSTRAINT pk_crdcredit PRIMARY KEY (k_branch, k_cred);
CREATE UNIQUE INDEX IF NOT EXISTS indcrdcredit1 ON keplersc.crdcredit USING btree (k_branch, k_cust, k_cred) TABLESPACE pg_default;

