CREATE  TABLE keplersc.ifz_parts_shipper_embarque (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ship_date timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  documento_id character varying(10) NOT NULL DEFAULT ''::character varying,
  procesado character varying NOT NULL DEFAULT 'N'::character varying,
  relacion_kdm1 character varying(20) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.ifz_parts_shipper_embarque ADD CONSTRAINT ifz_parts_shipper_embarque_pkey PRIMARY KEY (id);
COMMENT ON TABLE keplersc.ifz_parts_shipper_embarque IS 'Cabecera de embarques. Contiene la información general del envío.';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_embarque.ship_date IS 'Fecha en la que se realiza el envío del embarque';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_embarque.relacion_kdm1 IS 'Relación con KDMM1 (si aplica)';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_embarque.procesado IS 'Indica si el embarque ya fue procesado (S/N)';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_embarque.id IS 'Identificador único del embarque';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_embarque.documento_id IS 'Identificador del embarque';

