CREATE  TABLE keplersc.kdenttec (
  c1 character varying(7) NULL,
  c2 numeric NULL,
  c3 character varying(10) NULL,
  c4 character varying(5) NULL,
  c5 character varying(1) NULL,
  c6 character varying(10) NULL,
  c7 timestamp without time zone NOT NULL,
  c8 character varying(5) NULL,
  c9 character varying(5) NULL,
  c10 character varying(80) NULL,
  c11 character varying(80) NULL,
  c12 character varying(80) NULL,
  c13 character varying(80) NULL,
  c14 character varying(80) NULL,
  c15 character varying(1) NULL,
  c16 numeric NULL,
  c17 timestamp without time zone NOT NULL,
  c18 character varying(7) NULL,
  c19 character varying(80) NULL,
  c20 character varying(80) NULL,
  c21 character varying(30) NULL,
  c22 character varying(30) NULL,
  c23 character varying(1) NULL,
  c24 character varying(7) NULL,
  c25 numeric NULL,
  c26 numeric NULL,
  c27 numeric NULL,
  c28 numeric NULL,
  c29 character varying(1) NULL,
  c30 character varying(1) NULL,
  c31 character varying(1) NULL,
  c32 character varying(1) NULL,
  c33 character varying(1) NULL,
  c34 character varying(1) NULL,
  c35 character varying(1) NULL,
  c36 character varying(1) NULL,
  c37 character varying(1) NULL,
  c38 character varying(1) NULL,
  c39 character varying(30) NULL,
  c40 character varying(30) NULL,
  c41 character varying(30) NULL,
  c42 character varying(7) NULL,
  c43 character varying(7) NULL,
  c44 character varying(80) NULL,
  c45 character varying(80) NULL,
  c46 character varying(80) NULL,
  c47 character varying(10) NULL,
  c48 character varying(10) NULL,
  c49 character varying(1) NULL,
  c50 character varying(50) NULL,
  c51 character varying(80) NULL,
  c52 character varying(80) NULL,
  c53 character varying(80) NULL,
  c54 character varying(10) NULL,
  c55 character varying(10) NULL
) TABLESPACE pg_default;

