CREATE  TABLE keplersc.kdfe33m1 (
  c1 character varying(7) NOT NULL DEFAULT ''::character varying,
  c2 character varying(10) NOT NULL DEFAULT ''::character varying,
  c3 character varying(20) NOT NULL DEFAULT ''::character varying,
  c4 numeric NOT NULL DEFAULT 0,
  c5 character varying(1) NOT NULL DEFAULT ''::character varying,
  c6 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c7 character varying(20) NOT NULL DEFAULT ''::character varying,
  c8 character varying(1) NOT NULL DEFAULT ''::character varying,
  c9 character varying(1) NOT NULL DEFAULT ''::character varying,
  c10 character varying(1) NOT NULL DEFAULT ''::character varying,
  c11 numeric NOT NULL DEFAULT 0,
  c12 numeric NOT NULL DEFAULT 0,
  c13 character varying(7) NOT NULL DEFAULT ''::character varying,
  c14 character varying(1) NOT NULL DEFAULT ''::character varying,
  c15 character varying(5) NOT NULL DEFAULT ''::character varying,
  c16 character varying(8) NOT NULL DEFAULT ''::character varying,
  c17 character varying(20) NOT NULL DEFAULT ''::character varying,
  c18 character varying(60) NOT NULL DEFAULT ''::character varying,
  c19 numeric(20,6) NOT NULL DEFAULT 0,
  c20 numeric(20,6) NOT NULL DEFAULT 0,
  c21 character varying(8) NOT NULL DEFAULT ''::character varying,
  c22 numeric(20,6) NOT NULL DEFAULT 0,
  c23 numeric NOT NULL DEFAULT 0,
  c24 numeric(20,6) NOT NULL DEFAULT 0,
  c25 character varying(8) NOT NULL DEFAULT ''::character varying,
  c26 character varying(8) NOT NULL DEFAULT ''::character varying,
  c27 character varying(10) NOT NULL DEFAULT ''::character varying,
  c28 character varying(6) NOT NULL DEFAULT ''::character varying,
  c29 character varying(1) NOT NULL DEFAULT ''::character varying,
  c30 character varying(13) NOT NULL DEFAULT ''::character varying,
  c31 character varying(70) NOT NULL DEFAULT ''::character varying,
  c32 character varying(8) NOT NULL DEFAULT ''::character varying,
  c33 character varying(1) NOT NULL DEFAULT ''::character varying,
  c34 character varying(40) NOT NULL DEFAULT ''::character varying,
  c35 character varying(70) NOT NULL DEFAULT ''::character varying,
  c36 character varying(10) NOT NULL DEFAULT ''::character varying,
  c37 character varying(40) NOT NULL DEFAULT ''::character varying,
  c38 character varying(8) NOT NULL DEFAULT ''::character varying,
  c39 character varying(1) NOT NULL DEFAULT ''::character varying,
  c40 numeric(20,6) NOT NULL DEFAULT 0,
  c41 numeric(20,6) NOT NULL DEFAULT 0,
  c42 numeric(20,6) NOT NULL DEFAULT 0,
  c43 numeric(20,6) NOT NULL DEFAULT 0,
  c44 numeric(20,6) NOT NULL DEFAULT 0,
  c45 character varying(1) NOT NULL DEFAULT ''::character varying,
  c46 character varying(200) NOT NULL DEFAULT ''::character varying,
  c47 character varying(150) NOT NULL DEFAULT ''::character varying,
  c48 character varying(100) NOT NULL DEFAULT ''::character varying,
  c49 character varying(100) NOT NULL DEFAULT ''::character varying,
  c50 character varying(20) NOT NULL DEFAULT ''::character varying,
  c51 character varying(100) NOT NULL DEFAULT ''::character varying,
  c52 character varying(1) NOT NULL DEFAULT ''::character varying,
  c53 character varying(5) NOT NULL DEFAULT ''::character varying,
  c54 character varying(36) NOT NULL DEFAULT ''::character varying,
  c55 character varying(20) NOT NULL DEFAULT ''::character varying,
  c56 character varying(20) NOT NULL DEFAULT ''::character varying,
  c57 character varying(200) NOT NULL DEFAULT ''::character varying,
  c58 character varying(150) NOT NULL DEFAULT ''::character varying,
  c59 character varying(30) NOT NULL DEFAULT ''::character varying,
  c60 character varying(13) NOT NULL DEFAULT ''::character varying,
  c61 character varying(70) NOT NULL DEFAULT ''::character varying,
  c62 character varying(1) NOT NULL DEFAULT ''::character varying,
  c63 numeric NOT NULL DEFAULT 0,
  c64 character varying(20) NOT NULL DEFAULT ''::character varying,
  c65 character varying(20) NOT NULL DEFAULT ''::character varying,
  c66 character varying(30) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdfe33m1 ADD CONSTRAINT pk_kdfe33m1 PRIMARY KEY (c1, c2, c3);
CREATE INDEX IF NOT EXISTS sindkdfe33m102 ON keplersc.kdfe33m1 USING btree (c2, c3, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfe33m103 ON keplersc.kdfe33m1 USING btree (c1, c9, c10, c11, c12, c13) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfe33m104 ON keplersc.kdfe33m1 USING btree (c17, c1, c2, c3) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfe33m105 ON keplersc.kdfe33m1 USING btree (c4, c10, c2, c3, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdfe33m106 ON keplersc.kdfe33m1 USING btree (c54, c1, c2, c3) TABLESPACE pg_default;

