CREATE  TABLE keplersc.kdii (
  c1 character varying(18) NOT NULL DEFAULT ''::character varying,
  c2 character varying(40) NOT NULL DEFAULT ''::character varying,
  c3 character varying(5) NOT NULL DEFAULT ''::character varying,
  c4 character varying(5) NOT NULL DEFAULT ''::character varying,
  c5 character varying(5) NOT NULL DEFAULT ''::character varying,
  c6 character varying(18) NOT NULL DEFAULT ''::character varying,
  c7 character varying(18) NOT NULL DEFAULT ''::character varying,
  c8 character varying(7) NOT NULL DEFAULT ''::character varying,
  c9 character varying(7) NOT NULL DEFAULT ''::character varying,
  c10 character varying(7) NOT NULL DEFAULT ''::character varying,
  c11 character varying(3) NOT NULL DEFAULT ''::character varying,
  c12 character varying(3) NOT NULL DEFAULT ''::character varying,
  c13 double precision NOT NULL DEFAULT 0,
  c14 numeric(13,2) NOT NULL DEFAULT 0,
  c15 numeric(13,2) NOT NULL DEFAULT 0,
  c16 numeric(13,2) NOT NULL DEFAULT 0,
  c17 numeric(13,2) NOT NULL DEFAULT 0,
  c18 double precision NOT NULL DEFAULT 0,
  c19 double precision NOT NULL DEFAULT 0,
  c20 character varying(5) NOT NULL DEFAULT ''::character varying,
  c21 character varying(1) NOT NULL DEFAULT ''::character varying,
  c22 character varying(1) NOT NULL DEFAULT ''::character varying,
  c23 numeric(15,2) NOT NULL DEFAULT 0,
  c24 double precision NOT NULL DEFAULT 0,
  c25 character varying(18) NOT NULL DEFAULT ''::character varying,
  c26 character varying(18) NOT NULL DEFAULT ''::character varying,
  c27 character varying(1) NOT NULL DEFAULT ''::character varying,
  c28 character varying(17) NOT NULL DEFAULT ''::character varying,
  c29 double precision NOT NULL DEFAULT 0,
  c30 character varying(7) NOT NULL DEFAULT ''::character varying,
  c31 character varying(5) NOT NULL DEFAULT ''::character varying,
  c32 character varying(60) NOT NULL DEFAULT ''::character varying,
  c33 numeric NOT NULL DEFAULT 0,
  c34 numeric NOT NULL DEFAULT 0,
  c35 numeric NOT NULL DEFAULT 0,
  c36 numeric NOT NULL DEFAULT 0,
  c37 character varying(5) NOT NULL DEFAULT ''::character varying,
  c38 character varying(5) NOT NULL DEFAULT ''::character varying,
  c39 character varying(60) NOT NULL DEFAULT ''::character varying,
  c40 character varying(60) NOT NULL DEFAULT ''::character varying,
  c41 character varying(60) NOT NULL DEFAULT ''::character varying,
  c42 double precision NOT NULL DEFAULT 0,
  c43 character varying(1) NOT NULL DEFAULT ''::character varying,
  c44 numeric NOT NULL DEFAULT 0,
  c45 character varying(20) NOT NULL DEFAULT ''::character varying,
  c46 character varying(3) NOT NULL DEFAULT ''::character varying,
  c47 character varying(3) NOT NULL DEFAULT ''::character varying,
  c48 character varying(1) NOT NULL DEFAULT ''::character varying,
  c49 character varying(1) NOT NULL DEFAULT ''::character varying,
  c50 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c51 character varying(1) NOT NULL DEFAULT ''::character varying,
  c52 numeric NOT NULL DEFAULT 0,
  c53 numeric NOT NULL DEFAULT 0,
  c54 numeric NOT NULL DEFAULT 0,
  c55 numeric NOT NULL DEFAULT 0,
  c56 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c57 numeric NOT NULL DEFAULT 0,
  c58 numeric NOT NULL DEFAULT 0,
  c59 numeric NOT NULL DEFAULT 0,
  c60 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c61 numeric NOT NULL DEFAULT 0,
  c62 numeric NOT NULL DEFAULT 0,
  c63 numeric NOT NULL DEFAULT 0,
  c64 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c65 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c66 double precision NOT NULL DEFAULT 0,
  c67 numeric NOT NULL DEFAULT 0,
  c68 numeric NOT NULL DEFAULT 0,
  c69 character varying(1) NOT NULL DEFAULT ''::character varying,
  c70 character varying(30) NOT NULL DEFAULT ''::character varying,
  c71 character varying(1) NOT NULL DEFAULT ''::character varying,
  c72 character varying(1) NOT NULL DEFAULT ''::character varying,
  c73 character varying(1) NOT NULL DEFAULT ''::character varying,
  c74 character varying(1) NOT NULL DEFAULT ''::character varying,
  c75 character varying(1) NOT NULL DEFAULT ''::character varying,
  c76 character varying(1) NOT NULL DEFAULT ''::character varying,
  c77 character varying(1) NOT NULL DEFAULT ''::character varying,
  c78 character varying(1) NOT NULL DEFAULT ''::character varying,
  c79 character varying(1) NOT NULL DEFAULT ''::character varying,
  c80 character varying(1) NOT NULL DEFAULT ''::character varying,
  c81 character varying(1) NOT NULL DEFAULT ''::character varying,
  c82 character varying(1) NOT NULL DEFAULT ''::character varying,
  c83 character varying(1) NOT NULL DEFAULT ''::character varying,
  c84 character varying(1) NOT NULL DEFAULT ''::character varying,
  c85 character varying(1) NOT NULL DEFAULT ''::character varying,
  c86 character varying(1) NOT NULL DEFAULT ''::character varying,
  c87 character varying(1) NOT NULL DEFAULT ''::character varying,
  c88 character varying(1) NOT NULL DEFAULT ''::character varying,
  c89 character varying(1) NOT NULL DEFAULT ''::character varying,
  c90 character varying(1) NOT NULL DEFAULT ''::character varying,
  c91 character varying(1) NOT NULL DEFAULT ''::character varying,
  c92 character varying(1) NOT NULL DEFAULT ''::character varying,
  c93 character varying(1) NOT NULL DEFAULT ''::character varying,
  c94 character varying(1) NOT NULL DEFAULT ''::character varying,
  c95 character varying(1) NOT NULL DEFAULT ''::character varying,
  c96 character varying(1) NOT NULL DEFAULT ''::character varying,
  c97 character varying(1) NOT NULL DEFAULT ''::character varying,
  c98 character varying(1) NOT NULL DEFAULT ''::character varying,
  c99 character varying(1) NOT NULL DEFAULT ''::character varying,
  c100 character varying(1) NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdii ADD CONSTRAINT pk_kdii PRIMARY KEY (c1);
CREATE INDEX IF NOT EXISTS sindkdii02 ON keplersc.kdii USING btree (c2, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdii03 ON keplersc.kdii USING btree (c3, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdii04 ON keplersc.kdii USING btree (c4, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdii05 ON keplersc.kdii USING btree (c5, c1) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdii06 ON keplersc.kdii USING btree (c9) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS sindkdii07 ON keplersc.kdii USING btree (c7) TABLESPACE pg_default;

