CREATE  TABLE keplersc.kdik (
  c1 character varying(7) NOT NULL DEFAULT ''::character varying,
  c2 character varying(18) NOT NULL DEFAULT ''::character varying,
  c3 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c4 double precision NOT NULL DEFAULT 0,
  c5 double precision NOT NULL DEFAULT 0,
  c6 double precision NOT NULL DEFAULT 0,
  c7 numeric(15,2) NOT NULL DEFAULT 0,
  c8 numeric(15,2) NOT NULL DEFAULT 0,
  c9 numeric(15,2) NOT NULL DEFAULT 0,
  c10 numeric(15,2) NOT NULL DEFAULT 0,
  c11 numeric(15,2) NOT NULL DEFAULT 0,
  c12 numeric(15,2) NOT NULL DEFAULT 0,
  c13 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c14 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c15 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c16 double precision NOT NULL DEFAULT 0,
  c17 timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  c18 double precision NOT NULL DEFAULT 0,
  c19 double precision NOT NULL DEFAULT 0,
  c20 character varying(1) NOT NULL DEFAULT ''::character varying,
  c21 character varying(1) NOT NULL DEFAULT ''::character varying,
  c22 double precision NOT NULL DEFAULT 0,
  c23 double precision NOT NULL DEFAULT 0,
  c24 double precision NOT NULL DEFAULT 0,
  c25 double precision NOT NULL DEFAULT 0,
  c26 double precision NOT NULL DEFAULT 0,
  c27 double precision NOT NULL DEFAULT 0,
  c28 double precision NOT NULL DEFAULT 0,
  c29 double precision NOT NULL DEFAULT 0,
  c30 double precision NOT NULL DEFAULT 0,
  c31 double precision NOT NULL DEFAULT 0,
  c32 double precision NOT NULL DEFAULT 0,
  c33 double precision NOT NULL DEFAULT 0,
  c34 numeric(15,2) NOT NULL DEFAULT 0,
  c35 numeric(15,2) NOT NULL DEFAULT 0,
  c36 numeric(15,2) NOT NULL DEFAULT 0,
  c37 numeric(15,2) NOT NULL DEFAULT 0,
  c38 numeric(15,2) NOT NULL DEFAULT 0,
  c39 numeric(15,2) NOT NULL DEFAULT 0,
  c40 numeric(15,2) NOT NULL DEFAULT 0,
  c41 numeric(15,2) NOT NULL DEFAULT 0,
  c42 numeric(15,2) NOT NULL DEFAULT 0,
  c43 numeric(15,2) NOT NULL DEFAULT 0,
  c44 numeric(15,2) NOT NULL DEFAULT 0,
  c45 numeric(15,2) NOT NULL DEFAULT 0,
  c46 numeric(15,2) NOT NULL DEFAULT 0,
  c47 numeric(15,2) NOT NULL DEFAULT 0,
  c48 numeric(15,2) NOT NULL DEFAULT 0,
  c49 numeric(15,2) NOT NULL DEFAULT 0,
  c50 numeric(15,2) NOT NULL DEFAULT 0,
  c51 numeric(15,2) NOT NULL DEFAULT 0,
  c52 numeric(15,2) NOT NULL DEFAULT 0,
  c53 numeric(15,2) NOT NULL DEFAULT 0,
  c54 numeric(15,2) NOT NULL DEFAULT 0,
  c55 numeric(15,2) NOT NULL DEFAULT 0,
  c56 numeric(15,2) NOT NULL DEFAULT 0,
  c57 numeric(15,2) NOT NULL DEFAULT 0,
  c58 character varying(1) NOT NULL DEFAULT ''::character varying,
  c59 character varying(1) NOT NULL DEFAULT ''::character varying,
  c60 double precision NOT NULL DEFAULT 0,
  c61 double precision NOT NULL DEFAULT 0,
  c62 double precision NOT NULL DEFAULT 0,
  c63 double precision NOT NULL DEFAULT 0,
  c64 character varying(1) NOT NULL DEFAULT ''::character varying,
  c65 numeric(15,2) NOT NULL DEFAULT 0,
  c66 numeric(15,2) NOT NULL DEFAULT 0,
  c67 numeric(15,2) NOT NULL DEFAULT 0,
  c68 numeric(15,2) NOT NULL DEFAULT 0,
  c69 numeric(15,2) NOT NULL DEFAULT 0,
  c70 character varying(1) NOT NULL DEFAULT ''::character varying,
  c71 character varying(1) NOT NULL DEFAULT ''::character varying,
  c72 character varying(1) NOT NULL DEFAULT ''::character varying,
  c73 character varying(1) NOT NULL DEFAULT ''::character varying,
  c74 character varying(1) NOT NULL DEFAULT ''::character varying,
  c75 character varying(1) NOT NULL DEFAULT ''::character varying,
  c76 character varying(1) NOT NULL DEFAULT ''::character varying,
  c77 character varying(1) NOT NULL DEFAULT ''::character varying,
  c78 character varying(1) NOT NULL DEFAULT ''::character varying,
  c79 character varying(1) NOT NULL DEFAULT ''::character varying,
  c80 character varying(1) NOT NULL DEFAULT ''::character varying,
  c81 character varying(1) NOT NULL DEFAULT ''::character varying,
  c82 character varying(1) NOT NULL DEFAULT ''::character varying,
  c83 character varying(1) NOT NULL DEFAULT ''::character varying,
  c84 character varying(1) NOT NULL DEFAULT ''::character varying,
  c85 character varying(1) NOT NULL DEFAULT ''::character varying,
  c86 character varying(1) NOT NULL DEFAULT ''::character varying,
  c87 character varying(1) NOT NULL DEFAULT ''::character varying,
  c88 character varying(1) NOT NULL DEFAULT ''::character varying,
  c89 character varying(1) NOT NULL DEFAULT ''::character varying,
  c90 character varying(1) NOT NULL DEFAULT ''::character varying,
  c91 character varying(1) NOT NULL DEFAULT ''::character varying,
  c92 character varying(1) NOT NULL DEFAULT ''::character varying,
  c93 character varying(1) NOT NULL DEFAULT ''::character varying,
  c94 character varying(1) NOT NULL DEFAULT ''::character varying,
  c95 character varying(1) NOT NULL DEFAULT ''::character varying,
  c96 character varying(1) NOT NULL DEFAULT ''::character varying,
  c97 character varying(1) NOT NULL DEFAULT ''::character varying,
  c98 character varying(1) NOT NULL DEFAULT ''::character varying,
  c99 character varying(1) NOT NULL DEFAULT ''::character varying,
  c100 double precision NOT NULL DEFAULT 0,
  c101 double precision NOT NULL DEFAULT 0,
  c102 double precision NOT NULL DEFAULT 0,
  c103 double precision NOT NULL DEFAULT 0,
  c104 character varying(1) NOT NULL DEFAULT ''::character varying,
  c105 numeric(15,2) NOT NULL DEFAULT 0,
  c106 numeric(15,2) NOT NULL DEFAULT 0,
  c107 numeric(15,2) NOT NULL DEFAULT 0,
  c108 numeric(15,2) NOT NULL DEFAULT 0,
  c109 numeric(15,2) NOT NULL DEFAULT 0
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.kdik ADD CONSTRAINT pk_kdik PRIMARY KEY (c1, c2);

