CREATE  TABLE keplersc.totpas_1 (
  c1 character varying(7) NULL,
  c2 character varying(10) NULL,
  c3 character varying(20) NULL,
  c4 character varying(7) NULL,
  c5 character varying(10) NULL,
  c6 character varying(8) NULL,
  c7 character varying(5) NULL,
  c8 character varying(10) NULL,
  c9 character varying(17) NULL,
  c10 character varying(4) NULL,
  c11 numeric NULL,
  c12 timestamp without time zone NULL,
  c13 character varying(5) NULL,
  c14 timestamp without time zone NULL,
  c15 character varying(5) NULL,
  c16 timestamp without time zone NULL,
  c17 character varying(6) NULL,
  c18 character varying(1) NULL,
  c19 character varying(1) NULL,
  c20 numeric NULL,
  c21 character varying(1) NULL,
  c22 character varying(10) NULL,
  c23 character varying(6) NULL,
  c24 character varying(10) NULL,
  c25 character varying(1) NULL,
  c26 timestamp without time zone NULL,
  c27 character varying(5) NULL,
  c28 character varying(50) NULL,
  c29 character varying(1) NULL,
  c30 character varying(90) NULL,
  c31 character varying(90) NULL,
  c32 character varying(90) NULL,
  c33 character varying(90) NULL,
  c34 character varying(90) NULL,
  c35 character varying(90) NULL,
  c36 character varying(15) NULL,
  c37 character varying(1) NULL,
  c38 character varying(1) NULL,
  c39 character varying(1) NULL,
  c40 character varying(1) NULL
) TABLESPACE pg_default;

