CREATE  TABLE keplersc.control_de_citas_20 (
  col_fecha timestamp without time zone NOT NULL DEFAULT '1800-01-01 00:00:00'::timestamp without time zone,
  col_clave_operador character varying NOT NULL DEFAULT ''::character varying,
  col_nombre_ope character varying NOT NULL DEFAULT ''::character varying,
  col_tipo_ope character varying NOT NULL DEFAULT ''::character varying,
  h_07_00 character varying NOT NULL DEFAULT ''::character varying,
  h_07_20 character varying NOT NULL DEFAULT ''::character varying,
  h_07_40 character varying NOT NULL DEFAULT ''::character varying,
  h_08_00 character varying NOT NULL DEFAULT ''::character varying,
  h_08_20 character varying NOT NULL DEFAULT ''::character varying,
  h_08_40 character varying NOT NULL DEFAULT ''::character varying,
  h_09_00 character varying NOT NULL DEFAULT ''::character varying,
  h_09_20 character varying NOT NULL DEFAULT ''::character varying,
  h_09_40 character varying NOT NULL DEFAULT ''::character varying,
  h_10_00 character varying NOT NULL DEFAULT ''::character varying,
  h_10_20 character varying NOT NULL DEFAULT ''::character varying,
  h_10_40 character varying NOT NULL DEFAULT ''::character varying,
  h_11_00 character varying NOT NULL DEFAULT ''::character varying,
  h_11_20 character varying NOT NULL DEFAULT ''::character varying,
  h_11_40 character varying NOT NULL DEFAULT ''::character varying,
  h_12_00 character varying NOT NULL DEFAULT ''::character varying,
  h_12_20 character varying NOT NULL DEFAULT ''::character varying,
  h_12_40 character varying NOT NULL DEFAULT ''::character varying,
  h_13_00 character varying NOT NULL DEFAULT ''::character varying,
  h_13_20 character varying NOT NULL DEFAULT ''::character varying,
  h_13_40 character varying NOT NULL DEFAULT ''::character varying,
  h_14_00 character varying NOT NULL DEFAULT ''::character varying,
  h_14_20 character varying NOT NULL DEFAULT ''::character varying,
  h_14_40 character varying NOT NULL DEFAULT ''::character varying,
  h_15_00 character varying NOT NULL DEFAULT ''::character varying,
  h_15_20 character varying NOT NULL DEFAULT ''::character varying,
  h_15_40 character varying NOT NULL DEFAULT ''::character varying,
  h_16_00 character varying NOT NULL DEFAULT ''::character varying,
  h_16_20 character varying NOT NULL DEFAULT ''::character varying,
  h_16_40 character varying NOT NULL DEFAULT ''::character varying,
  h_17_00 character varying NOT NULL DEFAULT ''::character varying,
  h_17_20 character varying NOT NULL DEFAULT ''::character varying,
  h_17_40 character varying NOT NULL DEFAULT ''::character varying,
  h_18_00 character varying NOT NULL DEFAULT ''::character varying,
  h_18_20 character varying NOT NULL DEFAULT ''::character varying,
  h_18_40 character varying NOT NULL DEFAULT ''::character varying,
  h_19_00 character varying NOT NULL DEFAULT ''::character varying,
  h_19_20 character varying NOT NULL DEFAULT ''::character varying,
  h_19_40 character varying NOT NULL DEFAULT ''::character varying,
  h_20_00 character varying NOT NULL DEFAULT ''::character varying,
  h_20_20 character varying NOT NULL DEFAULT ''::character varying,
  h_20_40 character varying NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
CREATE UNIQUE INDEX IF NOT EXISTS control_de_citas_20_fecha_idx ON keplersc.control_de_citas_20 USING btree (col_fecha, col_clave_operador) TABLESPACE pg_default;
COMMENT ON TABLE keplersc.control_de_citas_20 IS 'panorama de horarios de citas de los operadores intervalo 20';

