CREATE  TABLE keplersc.ifz_parts_shipper_piezas (
  id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  shipment_id integer NOT NULL,
  item_id character varying(20) NOT NULL DEFAULT ''::character varying,
  item_description character varying(100) NOT NULL DEFAULT ''::character varying,
  order_quantity numeric NOT NULL DEFAULT 0,
  backorder_quantity numeric NOT NULL DEFAULT 0,
  shipped_quantity numeric NOT NULL DEFAULT 0,
  charge_amount numeric(9,2) NOT NULL DEFAULT 0,
  currency character varying NOT NULL DEFAULT ''::character varying,
  price_descripcion character varying NOT NULL DEFAULT 'Unit Price'::character varying,
  manufacturer_order_number character varying NOT NULL DEFAULT ''::character varying,
  dealer_order_number character varying NOT NULL DEFAULT ''::character varying
) TABLESPACE pg_default;
ALTER TABLE ONLY keplersc.ifz_parts_shipper_piezas ADD CONSTRAINT ifz_parts_shipper_piezas_pkey PRIMARY KEY (id);
ALTER TABLE ONLY keplersc.ifz_parts_shipper_piezas ADD CONSTRAINT fk_embarque FOREIGN KEY (shipment_id) REFERENCES keplersc.ifz_parts_shipper_embarque(id) ON DELETE CASCADE;

COMMENT ON TABLE keplersc.ifz_parts_shipper_piezas IS 'Detalle de piezas de cada embarque. Contiene las piezas incluidas en el envío.';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.shipped_quantity IS 'Cantidad de piezas que fueron enviadas en el embarque';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.shipment_id IS 'Identificador del embarque al que pertenece la pieza';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.price_descripcion IS 'Tipo de precio';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.order_quantity IS 'Cantidad de piezas que contenía la orden original';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.manufacturer_order_number IS 'Número de orden del fabricante';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.item_id IS 'Identificador de pieza';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.item_description IS 'Descripción de la pieza';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.id IS 'Identificador único de la pieza';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.dealer_order_number IS 'Número de orden del distribuidor';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.currency IS 'Moneda';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.charge_amount IS 'Costo por unidad';
COMMENT ON COLUMN keplersc.ifz_parts_shipper_piezas.backorder_quantity IS 'Cantidad de piezas en backorder';

